# Generated by Django 2.0.8 on 2019-01-08 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter_subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('userid', models.IntegerField(editable=False, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('is_templar', models.BooleanField(default=False)),
                ('is_alchemist', models.BooleanField(default=False)),
                ('is_scholar', models.BooleanField(default=False)),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Object_hierachy_tree_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_hierachy_tree', models.TextField()),
                ('timestamp', models.DateTimeField(editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('specification', models.TextField()),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('is_private', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Uploaded_dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('sep', models.CharField(blank=True, max_length=3, null=True)),
                ('encoding', models.CharField(blank=True, max_length=10, null=True)),
                ('quotechar', models.CharField(blank=True, max_length=1, null=True)),
                ('escapechar', models.CharField(blank=True, max_length=1, null=True)),
                ('na_values', models.TextField(blank=True, null=True)),
                ('skiprows', models.CharField(blank=True, max_length=20, null=True)),
                ('header', models.CharField(blank=True, max_length=10, null=True)),
                ('data_table_json', models.TextField()),
                ('data_source', models.TextField(null=True)),
                ('data_generation_date', models.DateField(null=True)),
                ('correctness_of_data', models.IntegerField(null=True)),
                ('context_specification', models.TextField()),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
