# Generated by Django 2.0.8 on 2019-01-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation_model',
            name='is_private',
        ),
    ]
