# Generated by Django 2.0.8 on 2019-01-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_uploaded_dataset_object_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object_hierachy_tree',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('parent', models.TextField()),
                ('text', models.TextField()),
                ('li_attr', models.TextField(null=True)),
                ('a_attr', models.TextField(null=True)),
            ],
        ),
    ]
