# Generated by Django 2.0.8 on 2018-11-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20181102_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter_subscriber',
            name='email_hash',
        ),
        migrations.AddField(
            model_name='newsletter_subscriber',
            name='created',
            field=models.DateTimeField(default='2018-11-01 12:25', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter_subscriber',
            name='updated',
            field=models.DateTimeField(default='2018-11-01 12:25', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter_subscriber',
            name='userid',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
