# Generated by Django 2.0.8 on 2018-11-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20181102_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter_subscriber',
            name='userid',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
