# Generated by Django 2.0.8 on 2018-11-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20181102_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter_subscriber',
            old_name='is_archivist',
            new_name='is_scholar',
        ),
    ]
