# Generated by Django 2.0.8 on 2018-11-13 21:38

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20181107_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('specification', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Uploaded_dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('specification', django.contrib.postgres.fields.jsonb.JSONField()),
                ('uploaded', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 13, 21, 38, 13, 321504), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 13, 21, 38, 13, 321504), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploaded_dataset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.User'),
        ),
        migrations.AddField(
            model_name='simulation_model',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.User'),
        ),
    ]
