# Generated by Django 2.0.8 on 2018-12-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_auto_20181117_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaded_dataset',
            name='user',
        ),
        migrations.DeleteModel(
            name='Uploaded_dataset',
        ),
    ]
