# Generated by Django 2.0.8 on 2018-12-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_uploaded_dataset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploaded_dataset',
            old_name='description',
            new_name='content_specification',
        ),
        migrations.RenameField(
            model_name='uploaded_dataset',
            old_name='specification',
            new_name='context_specification',
        ),
        migrations.RenameField(
            model_name='uploaded_dataset',
            old_name='uploaded',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='uploaded_dataset',
            name='slug',
        ),
        migrations.AddField(
            model_name='uploaded_dataset',
            name='updated',
            field=models.DateTimeField(default='2003-04-12 04:05:06', editable=False),
            preserve_default=False,
        ),
    ]
