# Generated by Django 2.0.8 on 2018-12-17 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_auto_20181205_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='uploaded_dataset',
            old_name='content_specification',
            new_name='data_table_json',
        ),
        migrations.RenameField(
            model_name='uploaded_dataset',
            old_name='name',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='uploaded_dataset',
            name='correctness_of_data',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploaded_dataset',
            name='data_generation_date',
            field=models.DateField(default='2018-12-17'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploaded_dataset',
            name='encoding',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uploaded_dataset',
            name='escapechar',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='uploaded_dataset',
            name='file_path',
            field=models.TextField(default='C:/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploaded_dataset',
            name='header',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uploaded_dataset',
            name='na_values',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploaded_dataset',
            name='quotechar',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='uploaded_dataset',
            name='sep',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='uploaded_dataset',
            name='skiprows',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uploaded_dataset',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.Datasource'),
        ),
    ]
