# Generated by Django 2.0.8 on 2018-12-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0015_auto_20181217_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_dataset',
            name='correctness_of_data',
            field=models.IntegerField(null=True),
        ),
    ]
