# Generated by Django 2.0.8 on 2018-12-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0016_auto_20181217_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_dataset',
            name='data_generation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_dataset',
            name='data_source',
            field=models.TextField(null=True),
        ),
    ]
